// src/app/components/contact/contact.component.ts
import { Component } from "@angular/core"
import { CommonModule } from "@angular/common"
import { FormsModule, NgForm } from "@angular/forms"
import { environment } from '../../../environments/environment';


@Component({
  selector: "app-contact",
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: "./contact.component.html",
  styleUrls: ["./contact.component.css"],
})
export class ContactComponent {
  formData = {
    name: "",
    email: "",
    subject: "",
    message: "",
  }
  
  // Property for displaying confirmation/error messages
  confirmation: string = ""

  async onSubmit(form: NgForm) {
    if (form.valid) {
      try {
        const response = await fetch(`${environment.domain}/message`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(this.formData),
        });
        if (!response.ok) {
          throw new Error('Failed to send message');
        }
        this.confirmation = "Thank you for your message! I'll get back to you soon."
        form.resetForm(); // Resets both model and form state
      } catch (error) {
        this.confirmation = "There was an error sending your message. Please try again later."
        console.error(error);
      }
    }
  }
}

<section id="contact" class="contact">
  <div class="container">
    <h2 class="section-title">Get In Touch</h2>
    <div class="contact-content">
      <div class="contact-info">
        <h3>Let's work together!</h3>
        <p>
          I'm always interested in new opportunities and exciting projects.
          Whether you have a question or just want to say hi, feel free to reach out!
        </p>
        <div class="contact-details">
          <div class="contact-item">
            <strong>Email:</strong>
            <a href="mailto:soroosh.esmaeilian@gmail.com">soroosh.esmaeilian&#64;gmail.com</a>
          </div>
          <div class="contact-item">
            <strong>Location:</strong>
            <span>Calgary, AB</span>
          </div>
        </div>
        <div class="social-links">
          <a href="https://github.com/Soroush98" target="_blank" class="social-link">GitHub</a>
          <a href="https://www.linkedin.com/in/sorooshes98/" target="_blank" class="social-link">LinkedIn</a>
          <a href="https://www.instagram.com/soroosh_es98" target="_blank" class="social-link">Instagram</a>
        </div>
      
        <div class="resume-section">
          <h4>Download My Resume</h4>
          <p>Get a detailed overview of my experience, skills, and achievements.</p>
          <a href="/Soroosh_Esmaeilian_FullStack.pdf" download="Soroosh_Esmaeilian_Resume.pdf" class="resume-download-btn">
            <span class="download-icon">📄</span>
            Download Resume (PDF)
          </a>
        </div>
      </div>
      <form class="contact-form" (ngSubmit)="onSubmit(contactForm)" #contactForm="ngForm">
        <!-- Add confirmation message above the form -->
        <div *ngIf="confirmation" class="confirmation-message">
          {{ confirmation }}
        </div>
        <div class="form-group">
          <label for="name">Name</label>
          <input
            type="text"
            id="name"
            name="name"
            [(ngModel)]="formData.name"
            required
            #name="ngModel"
          >
          <div *ngIf="name.invalid && name.touched" class="error">Name is required</div>
        </div>
        <div class="form-group">
          <label for="email">Email</label>
          <input
            type="email"
            id="email"
            name="email"
            [(ngModel)]="formData.email"
            required
            email
            #email="ngModel"
          >
          <div *ngIf="email.invalid && email.touched" class="error">Valid email is required</div>
        </div>
        <div class="form-group">
          <label for="subject">Subject</label>
          <input
            type="text"
            id="subject"
            name="subject"
            [(ngModel)]="formData.subject"
            required
            #subject="ngModel"
          >
          <div *ngIf="subject.invalid && subject.touched" class="error">Subject is required</div>
        </div>
        <div class="form-group">
          <label for="message">Message</label>
          <textarea
            id="message"
            name="message"
            rows="5"
            [(ngModel)]="formData.message"
            required
            #message="ngModel"
          ></textarea>
          <div *ngIf="message.invalid && message.touched" class="error">Message is required</div>
        </div>
        <button type="submit" class="btn btn-primary" [disabled]="contactForm.invalid">
          Send Message
        </button>
      </form>
    </div>
  </div>
</section>

// src/components/Contact/Contact.tsx
"use client";

import { useState, type FormEvent } from "react";
import styles from "./Contact.module.css";

type FormData = {
  name: string;
  email: string;
  subject: string;
  message: string;
};

const initial: FormData = { name: "", email: "", subject: "", message: "" };

export default function Contact() {
  const [formData, setFormData] = useState<FormData>(initial);
  const [touched, setTouched] = useState<Record<keyof FormData, boolean>>({
    name: false,
    email: false,
    subject: false,
    message: false,
  });
  const [confirmation, setConfirmation] = useState("");
  const [submitting, setSubmitting] = useState(false);

  const emailValid = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.email);
  const invalid = {
    name: !formData.name.trim(),
    email: !formData.email.trim() || !emailValid,
    subject: !formData.subject.trim(),
    message: !formData.message.trim(),
  };
  const formInvalid = invalid.name || invalid.email || invalid.subject || invalid.message;

  async function onSubmit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    if (formInvalid) return;
    setSubmitting(true);
    try {
      const response = await fetch("/api/message", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(formData),
      });
      if (!response.ok) throw new Error("Failed to send message");
      setConfirmation("Thank you for your message! I'll get back to you soon.");
      setFormData(initial);
      setTouched({ name: false, email: false, subject: false, message: false });
    } catch (err) {
      console.error(err);
      setConfirmation("There was an error sending your message. Please try again later.");
    } finally {
      setSubmitting(false);
    }
  }

  const update = (field: keyof FormData) => (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) =>
    setFormData((prev) => ({ ...prev, [field]: e.target.value }));

  const blur = (field: keyof FormData) => () => setTouched((prev) => ({ ...prev, [field]: true }));

  return (
    <section id="contact" className={styles.contact}>
      <div className={styles.container}>
        <h2 className={styles.sectionTitle}>Get In Touch</h2>
        <div className={styles.contactContent}>
          <div className={styles.contactInfo}>
            <h3>Let&apos;s work together!</h3>
            <p>
              I&apos;m always interested in new opportunities and exciting projects.
              Whether you have a question or just want to say hi, feel free to reach out!
            </p>
            <div className={styles.contactDetails}>
              <div className={styles.contactItem}>
                <strong>Email:</strong>
                <a href="mailto:soroosh.esmaeilian@gmail.com">soroosh.esmaeilian@gmail.com</a>
              </div>
              <div className={styles.contactItem}>
                <strong>Location:</strong>
                <span>Calgary, AB</span>
              </div>
            </div>
            <div className={styles.socialLinks}>
              <a href="https://github.com/Soroush98" target="_blank" rel="noopener noreferrer" className={styles.socialLink}>GitHub</a>
              <a href="https://www.linkedin.com/in/sorooshes98/" target="_blank" rel="noopener noreferrer" className={styles.socialLink}>LinkedIn</a>
              <a href="https://www.instagram.com/soroosh_es98" target="_blank" rel="noopener noreferrer" className={styles.socialLink}>Instagram</a>
            </div>
          </div>
          <form className={styles.contactForm} onSubmit={onSubmit} noValidate>
            {confirmation && <div className={styles.confirmationMessage}>{confirmation}</div>}
            <div className={styles.formGroup}>
              <label htmlFor="name">Name</label>
              <input
                type="text"
                id="name"
                name="name"
                value={formData.name}
                onChange={update("name")}
                onBlur={blur("name")}
                required
              />
              {invalid.name && touched.name && <div className={styles.error}>Name is required</div>}
            </div>
            <div className={styles.formGroup}>
              <label htmlFor="email">Email</label>
              <input
                type="email"
                id="email"
                name="email"
                value={formData.email}
                onChange={update("email")}
                onBlur={blur("email")}
                required
              />
              {invalid.email && touched.email && <div className={styles.error}>Valid email is required</div>}
            </div>
            <div className={styles.formGroup}>
              <label htmlFor="subject">Subject</label>
              <input
                type="text"
                id="subject"
                name="subject"
                value={formData.subject}
                onChange={update("subject")}
                onBlur={blur("subject")}
                required
              />
              {invalid.subject && touched.subject && <div className={styles.error}>Subject is required</div>}
            </div>
            <div className={styles.formGroup}>
              <label htmlFor="message">Message</label>
              <textarea
                id="message"
                name="message"
                rows={5}
                value={formData.message}
                onChange={update("message")}
                onBlur={blur("message")}
                required
              />
              {invalid.message && touched.message && <div className={styles.error}>Message is required</div>}
            </div>
            <button type="submit" className={styles.btn} disabled={formInvalid || submitting}>
              {submitting ? "Sending..." : "Send Message"}
            </button>
          </form>
        </div>
      </div>
    </section>
  );
}
