// src/app/components/header/header.component.ts
import { Component, HostListener } from "@angular/core"
import { CommonModule } from "@angular/common"

@Component({
  selector: "app-header",
  standalone: true,
  imports: [CommonModule],
  template: `
    <header class="header" [class.scrolled]="isScrolled">
      <div class="container">
        <div class="logo">
          <a href="#home">Soroosh Esmaeilian</a>
        </div>
        <nav class="nav" [class.active]="isMenuOpen">
          <a href="#home" (click)="closeMenu()">Home</a>
          <a href="#projects" (click)="closeMenu()">Projects</a>
          <a href="#skills" (click)="closeMenu()">Skills</a>
          <a href="#passion" (click)="closeMenu()">About</a>
          <a href="#education" (click)="closeMenu()">Education</a>
          <a href="#contact" (click)="closeMenu()">Contact</a>
        </nav>
        <div class="header-actions">
       
          <button class="menu-toggle" (click)="toggleMenu()" [class.active]="isMenuOpen">
            <span></span>
            <span></span>
            <span></span>
          </button>
        </div>
      </div>
    </header>
  `,
  styleUrls: ["./header.component.css"],
})
export class HeaderComponent {
  isScrolled = false
  isMenuOpen = false

  @HostListener("window:scroll", [])
  onWindowScroll() {
    this.isScrolled = window.pageYOffset > 50
  }

  toggleMenu() {
    this.isMenuOpen = !this.isMenuOpen
  }

  closeMenu() {
    this.isMenuOpen = false
  }
}

// src/components/Header/Header.tsx
"use client";

import { useEffect, useState } from "react";
import styles from "./Header.module.css";

export default function Header() {
  const [isScrolled, setIsScrolled] = useState(false);
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  useEffect(() => {
    const onScroll = () => setIsScrolled(window.pageYOffset > 50);
    window.addEventListener("scroll", onScroll);
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  const closeMenu = () => setIsMenuOpen(false);

  return (
    <header className={`${styles.header} ${isScrolled ? styles.scrolled : ""}`}>
      <div className={styles.container}>
        <div className={styles.logo}>
          <a href="#home">Soroosh Esmaeilian</a>
        </div>
        <nav className={`${styles.nav} ${isMenuOpen ? styles.active : ""}`}>
          <a href="#home" onClick={closeMenu}>Home</a>
          <a href="#projects" onClick={closeMenu}>Projects</a>
          <a href="#skills" onClick={closeMenu}>Skills</a>
          <a href="#passion" onClick={closeMenu}>About</a>
          <a href="#education" onClick={closeMenu}>Education</a>
          <a href="#contact" onClick={closeMenu}>Contact</a>
        </nav>
        <div className={styles.headerActions}>
          <button
            className={`${styles.menuToggle} ${isMenuOpen ? styles.active : ""}`}
            onClick={() => setIsMenuOpen((v) => !v)}
            aria-label="Toggle menu"
          >
            <span></span>
            <span></span>
            <span></span>
          </button>
        </div>
      </div>
    </header>
  );
}
